const { randomBytes } = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const version = randomBytes(64).toString('hex');

const outputDirectory = path.resolve('src/app/core');
const outputFile = path.join(outputDirectory, 'version.ts');

fs.mkdirSync(outputDirectory, { recursive: true });

const content = `
// This file is automatically generated during build.
// DO NOT EDIT MANUALLY.

export const APP_VERSION = "${version}";
`.trimStart();

fs.writeFileSync(outputFile, content, 'utf8');

console.log(`Generated SPA version: ${version}`);
